/*
card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id)
*/
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(1,'C001', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(2,'C002', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(3,'C003', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(4,'C004', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(5,'C005', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(6,'C006', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(7,'C007', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(8,'C008', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(9,'C009', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(10,'C010', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(11,'C011', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(12,'C012', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(13,'C013', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(14,'C014', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(15,'C015', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(16,'C016', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(17,'C017', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(18,'C018', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(19,'C019', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(20,'C020', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(21,'C021', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(22,'C022', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(23,'C023', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(24,'C024', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(25,'C025', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(26,'C026', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(27,'C027', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(28,'C028', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(29,'C029', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(30,'S001', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(31,'S002', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(32,'S003', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(33,'S004', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(34,'S005', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(35,'S006', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(36,'S007', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(37,'S008', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(38,'S009', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(39,'S010', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(40,'S011', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(41,'S012', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(42,'S013', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1108);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(43,'S014', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(44,'S015', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(45,'S016', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(46,'S017', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(47,'S018', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(48,'S019', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(49,'S020', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(50,'S021', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(51,'S022', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(52,'S023', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(53,'S024', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(54,'S025', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(55,'S026', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(56,'S027', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(57,'S028', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(58,'S029', 0, 1, 1, 1, SYSDATE, 'SYSTEM' , 1534);
INSERT INTO card(id, card_number, is_bsso_card, is_active, is_approved, edit_count, create_date, created_by, branch_sol_id) VALUES(59,'C030', 1, 1, 1, 1, SYSDATE, 'SYSTEM' , 1529);



select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;
select card_seq.nextval from dual;

